### PR TITLE
add arm64 to be downloaded when using helm plugin install

### LINKED ISSUE #34: helm plugin install does not support apple M1 with a prebuild binary
**Description**

The helm plugin install does not support M1 Macs without install via go/make. 

```bash
helm plugin install https://github.com/sigstore/helm-sigstore
Installing helm sigstore plugin
No prebuild binary for darwin-arm64.
Failed to install helm-sigstore
        For support, go to https://github.com/sigstore/helm-sigstore.
Error: plugin install hook for "sigstore" exited with error
Jamess-MBP-2:tekton-helm-chart strongjz$ 
```

Go/Make install works fine
```bash
 make
CGO_ENABLED=0 go build -trimpath -ldflags "-X github.com/sigstore/helm-sigstore/cmd.gitVersion=v0.1.3-3-gb2f9d36 -X github.com/sigstore/helm-sigstore/cmd.gitCommit=b2f9d365930e48f7e241fada51c3e703e4e81257 -X github.com/sigstore/helm-sigstore/cmd.gitTreeState="clean" -X github.com/sigstore/helm-sigstore/cmd.buildDate='2022-01-31T14:01:58Z'" -o '/Users/strongjz/Documents/code/go/src/github.com/sigstore/helm-sigstore/bin/helm-sigstore' .
go: downloading github.com/go-openapi/runtime v0.22.0
go: downloading github.com/go-openapi/swag v0.20.0
go: downloading github.com/sigstore/rekor v0.2.1-0.20210719011743-12077f5d7382
go: downloading golang.org/x/crypto v0.0.0-20210817164053-32db794688a5
go: downloading github.com/sigstore/sigstore v0.0.0-20210713222344-1fee53516622
go: downloading golang.org/x/mod v0.5.0
go: downloading github.com/go-playground/universal-translator v0.17.0
go: downloading go.uber.org/atomic v1.8.0
go: downloading golang.org/x/term v0.0.0-20210615171337-6886f2dfbf5b
go: downloading github.com/go-playground/locales v0.13.0
go: downloading golang.org/x/net v0.0.0-20210813160813-60bc85c4be6d
go: downloading github.com/theupdateframework/go-tuf v0.0.0-20210630170422-22a94818d17b
go: downloading github.com/google/go-containerregistry v0.5.1
Jamess-MBP-2:helm-sigstore strongjz$ helm plugin list
NAME            VERSION DESCRIPTION                                             
sigstore        0.1.3   This plugin integrates Helm into the Sigstore ecosystem.
```

### PR DESCRIPTION
**Pull request by cpanato**
#### Summary
add arm64 to be downloaded when using helm plugin install

#### Ticket Link

Fixes #34 

cc @strongjz

#### Release Note

```release-note
add arm64 to be downloaded when using helm plugin install
```

### CODE REVIEW

**Comment by cpanato** [comment]
gently ping @sabre1041

**Review by sabre1041 — APPROVED** [review]
LGTM

**Review by sabre1041 — CHANGES_REQUESTED** [review]
@cpanato Can we bump the plugin version so we can produce a new release?

**Comment by cpanato** [comment]
@sabre1041 done, PTAL

**Review by sabre1041 — APPROVED** [review]
LGTM

**Pull request merged**
