### PR TITLE
Add golangci-lint/check headers and fix lints

### PR DESCRIPTION
**Pull request by cpanato**
#### Summary
- Add golangci-lint/check headers and fix lints

#### Ticket Link
n/a

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Comment by sabre1041** [comment]
@cpanato this looks really good. Do we want to rebase it off of #21 once it is merged?

**Comment by cpanato** [comment]
@sabre1041 sure, i will rebase

**Comment by cpanato** [comment]
@sabre1041 rebased :)

**Review by sabre1041 — APPROVED** [review]
LGTM

**Pull request merged**
